


DATA ANALYSIS




In [79]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [80]:
data = pd.read_csv('New_Supplementary_Data1.csv')

In [81]:
data

Sample ID Cohort group  Age Sex  Weight [kg]  Height [cm] Tumour Site  \
0    WEU0043       cancer   59   F         77.2          160  Oesophagus   
1    WEU0044       cancer   70   M         61.5          175  Oesophagus   
2    WEU0046       cancer   54   M         86.0          180  Oesophagus   
3    WEU0047       cancer   70   M         79.5          180  Oesophagus   
4    WEU0048       cancer   55   M        101.5          177         OGJ   
..       ...          ...  ...  ..          ...          ...         ...   
57   WEU0122       cancer   63   F         52.4          153    Pancreas   
58   WEU0123       cancer   67   M         91.3          170    Pancreas   
59   WEU0184       cancer   76   M         72.4          173    Pancreas   
60   WEU0188       cancer   65   M         90.6          170         OGJ   
61   WEU0194       cancer   63   F         71.8          175  Oesophagus   

   Histology  Pre-op CRP level  Pre-op Bili  ...  Pre-op PLT  Pre-op WCC  \
0        SCC               1.0           17  ...       183.0         4.3   
1        ACC               0.9            9  ...       257.0         5.0   
2        ACC               3.0            4  ...       230.0         9.2   
3        ACC               2.0            8  ...       218.0        10.2   
4        ACC               2.0            6  ...       203.0         3.4   
..       ...               ...          ...  ...         ...         ...   
57       ACC               1.0           38  ...       209.0         5.2   
58       ACC               1.0           10  ...       291.0         7.7   
59       ACC               4.0           14  ...       211.0         6.3   
60       ACC               1.0            8  ...       276.0         6.3   
61       SCC               5.0           13  ...       192.0         7.6   

    Blood testosterone  Blood calc free testosterone  Blood oestradiol  \
0                  1.8                           207                50   
1                 12.0                           183                50   
2                 12.7                           257                72   
3                 23.1                           374               101   
4                 11.2                           228                64   
..                 ...                           ...               ...   
57                 1.6                           207                50   
58                12.5                           197                73   
59                26.8                           158                68   
60                 1.2                           207                60   
61                 1.4                           207                50   

    Blood LH  Blood FSH  Blood SHBG  Blood insulin  Blood cortisol  
0       38.3       36.3          92            7.7             492  
1       12.2       17.1          56            3.7             517  
2       12.3       15.8          36            8.0             210  
3       16.9       16.7          57            8.4             315  
4        2.9        5.8          36            7.8             401  
..       ...        ...         ...            ...             ...  
57      22.9       65.8          63            2.0             320  
58       8.7        6.9          51            6.4             260  
59      31.9       18.6         177            2.0             369  
60      21.0       62.2          70            7.5             559  
61      20.7       28.4         116            6.1             788  

[62 rows x 32 columns]

In [82]:
data.describe()

Age  Weight [kg]  Height [cm]  Pre-op CRP level  Pre-op Bili  \
count  62.000000    62.000000    62.000000         62.000000    62.000000   
mean   65.048387    75.362742   170.064516         15.270968    26.677419   
std     9.452951    17.690113     9.209530         33.384513    62.432593   
min    43.000000    41.400000   140.000000          0.900000     4.000000   
25%    59.000000    62.250000   165.250000          1.000000     6.000000   
50%    66.000000    75.350000   170.000000          3.000000     9.000000   
75%    70.750000    85.625000   175.000000          8.750000    14.000000   
max    83.000000   133.000000   190.000000        172.000000   342.000000   

       Pre-op ALT  Pre-op Alk Phos   Pre-op GGT  Pre-op Albumin  Pre-op Urea  \
count   62.000000        62.000000    62.000000       62.000000    62.000000   
mean    34.306452       149.274194   131.564516       34.306452     5.287097   
std     42.329151       190.674830   231.770776        3.977761     2.195859   
min      6.000000        24.000000     6.000000       22.000000     1.200000   
25%     13.000000        54.500000    19.250000       32.000000     3.600000   
50%     20.000000        82.000000    35.500000       35.000000     5.000000   
75%     29.750000       124.500000    93.750000       37.000000     6.400000   
max    241.000000       997.000000  1020.000000       42.000000    12.000000   

       ...  Pre-op PLT  Pre-op WCC  Blood testosterone  \
count  ...   62.000000   62.000000           62.000000   
mean   ...  292.067742   12.935484            8.996774   
std    ...  118.356294   42.811061            7.199772   
min    ...   10.200000    3.100000            0.500000   
25%    ...  219.750000    5.600000            1.425000   
50%    ...  266.000000    7.450000            9.150000   
75%    ...  324.750000    8.900000           13.225000   
max    ...  731.000000  344.000000           26.800000   

       Blood calc free testosterone  Blood oestradiol   Blood LH  Blood FSH  \
count                     62.000000         62.000000  62.000000  62.000000   
mean                     206.951613         77.322581  13.290323  21.322581   
std                       62.348683         33.524532   9.343758  18.815850   
min                       69.000000         50.000000   0.900000   1.100000   
25%                      189.750000         50.000000   6.000000   5.500000   
50%                      207.000000         63.500000  11.450000  16.900000   
75%                      207.000000         94.000000  18.900000  33.875000   
max                      429.000000        201.000000  39.200000  66.200000   

       Blood SHBG  Blood insulin  Blood cortisol  
count   62.000000      62.000000       62.000000  
mean    57.241935       7.312903      417.725806  
std     28.199340       5.653738      161.408977  
min     18.000000       2.000000      116.000000  
25%     36.250000       3.725000      293.750000  
50%     54.500000       6.300000      399.000000  
75%     66.000000       8.000000      524.500000  
max    177.000000      31.200000      925.000000  

[8 rows x 27 columns]

In [83]:
data.shape

(62, 32)

In [84]:
data['Tumour Site'].value_counts()

Tumour Site
Pancreas      23
Oesophagus    18
OGJ           11
Gastric       10
Name: count, dtype: int64

In [85]:
data['Histology'].value_counts()

Histology
ACC     57
SCC      4
ACC      1
Name: count, dtype: int64





DATA PROCESSING





In [86]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [87]:
categorical_columns = data.select_dtypes(include=['object']).columns
le = LabelEncoder()
for col in categorical_columns:
    data[col] = le.fit_transform(data[col])


In [88]:
X = data.drop(columns=['Tumour Site','Sample ID','Cohort group'])
X.head()

Age  Sex  Weight [kg]  Height [cm]  Histology  Pre-op CRP level  \
0   59    0         77.2          160          2               1.0   
1   70    1         61.5          175          0               0.9   
2   54    1         86.0          180          0               3.0   
3   70    1         79.5          180          0               2.0   
4   55    1        101.5          177          0               2.0   

   Pre-op Bili  Pre-op ALT  Pre-op Alk Phos  Pre-op GGT  ...  Pre-op PLT  \
0           17          12               53          15  ...       183.0   
1            9          12               46          27  ...       257.0   
2            4          11               56          24  ...       230.0   
3            8          28               78          30  ...       218.0   
4            6          11               39          32  ...       203.0   

   Pre-op WCC  Blood testosterone  Blood calc free testosterone  \
0         4.3                 1.8                           207   
1         5.0                12.0                           183   
2         9.2                12.7                           257   
3        10.2                23.1                           374   
4         3.4                11.2                           228   

   Blood oestradiol  Blood LH  Blood FSH  Blood SHBG  Blood insulin  \
0                50      38.3       36.3          92            7.7   
1                50      12.2       17.1          56            3.7   
2                72      12.3       15.8          36            8.0   
3               101      16.9       16.7          57            8.4   
4                64       2.9        5.8          36            7.8   

   Blood cortisol  
0             492  
1             517  
2             210  
3             315  
4             401  

[5 rows x 29 columns]

In [89]:
X.to_csv('X.csv', index=False)

In [90]:
features = X.columns
for feature in features:
    print(feature)

Age
Sex
Weight [kg]
Height [cm]
Histology
Pre-op CRP level
Pre-op Bili
Pre-op ALT
Pre-op Alk Phos
Pre-op GGT
Pre-op Albumin
Pre-op Urea
Pre-op Creatinine
Pre-op estimated GFR
Pre-op Na
Pre-op K
Pre-op TCO2
Pre-op Glucose
Pre-op Hb
Pre-op PLT
Pre-op WCC
Blood testosterone
Blood calc free testosterone
Blood oestradiol
Blood LH
Blood FSH
Blood SHBG
Blood insulin
Blood cortisol


In [91]:
y = data['Tumour Site']
y.head(20)

0     2
1     2
2     2
3     2
4     1
5     3
6     3
7     0
8     0
9     1
10    2
11    1
12    2
13    1
14    0
15    0
16    3
17    2
18    2
19    1
Name: Tumour Site, dtype: int64

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)




ML MODEL 1





In [93]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [94]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [95]:
Test = clf.predict(X_test)

In [96]:
Test

array([2, 2, 1, 3, 1, 3, 3, 3, 2, 3, 3, 3, 0, 3, 3, 2, 3, 1, 1])

In [97]:
y_test

23    2
37    1
49    2
16    3
10    2
25    3
42    3
7     0
6     3
45    3
31    3
27    3
40    1
39    3
35    3
18    2
33    1
19    1
4     1
Name: Tumour Site, dtype: int64

In [98]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [99]:
accuracy = accuracy_score(y_test,Test)
print("Model Accuracy = ",accuracy*100)

print("\n")

report = classification_report(y_test,Test)
print("Classification Report : \n",report)

Model Accuracy =  63.1578947368421


Classification Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.40      0.44         5
           2       0.50      0.50      0.50         4
           3       0.80      0.89      0.84         9

    accuracy                           0.63        19
   macro avg       0.45      0.45      0.45        19
weighted avg       0.62      0.63      0.62        19



In [100]:
matrix = confusion_matrix(y_test,Test)
matrix

array([[0, 0, 0, 1],
       [1, 2, 1, 1],
       [0, 2, 2, 0],
       [0, 0, 1, 8]])





ML MODEL 2





In [101]:
from sklearn.ensemble import RandomForestClassifier

In [102]:
clf2 = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=42)
clf2.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [103]:
Test2 = clf2.predict(X_test)

In [104]:
Test2

array([2, 2, 1, 3, 2, 3, 3, 2, 3, 3, 3, 3, 0, 3, 3, 2, 2, 1, 2])

In [105]:
accuracy2 = accuracy_score(y_test,Test2)
print("Model 2 Accuracy = ",accuracy2*100)

print("\n")

report2 = classification_report(y_test,Test2)
print("Classification Report 2: \n",report2)

Model 2 Accuracy =  68.42105263157895


Classification Report 2: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.20      0.29         5
           2       0.43      0.75      0.55         4
           3       1.00      1.00      1.00         9

    accuracy                           0.68        19
   macro avg       0.48      0.49      0.46        19
weighted avg       0.70      0.68      0.66        19



In [106]:
matrix2 = confusion_matrix(y_test,Test2)
matrix2

array([[0, 0, 1, 0],
       [1, 1, 3, 0],
       [0, 1, 3, 0],
       [0, 0, 0, 9]])





ML MODEL 3





In [107]:
from sklearn.svm import SVC

In [108]:
clf3 = SVC(kernel='linear', random_state=42)
clf3.fit(X_train, y_train)

SVC(kernel='linear', random_state=42)

In [109]:
Test3 = clf3.predict(X_test)

In [113]:
Test3

array([1, 0, 1, 3, 1, 1, 3, 1, 2, 1, 1, 3, 0, 1, 0, 2, 1, 1, 1])

In [110]:
accuracy3 = accuracy_score(y_test,Test3)
print("Model 3 Accuracy = ",accuracy3*100)

print("\n")

report3 = classification_report(y_test,Test3)
print("Classification Report 3: \n",report3)

Model 3 Accuracy =  36.84210526315789


Classification Report 3: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.27      0.60      0.37         5
           2       0.50      0.25      0.33         4
           3       1.00      0.33      0.50         9

    accuracy                           0.37        19
   macro avg       0.44      0.30      0.30        19
weighted avg       0.65      0.37      0.41        19



In [111]:
matrix3 = confusion_matrix(y_test,Test3)
matrix3

array([[0, 1, 0, 0],
       [2, 3, 0, 0],
       [0, 3, 1, 0],
       [1, 4, 1, 3]])





COMPARISON BETWEEN MODELS





In [112]:
print("Model 1 Accuracy = ",accuracy*100)
print("Model 2 Accuracy = ",accuracy2*100)
print("Model 3 Accuracy = ",accuracy3*100)

Model 1 Accuracy =  63.1578947368421
Model 2 Accuracy =  68.42105263157895
Model 3 Accuracy =  36.84210526315789


In [114]:
from joblib import dump

In [118]:
dump(clf,'./../savedModels/model.joblib')

['./../savedModels/model.joblib']

In [120]:
dump(clf2,'./../savedModels/model2.joblib')

['./../savedModels/model2.joblib']

In [121]:
dump(clf3,'./../savedModels/model3.joblib')

['./../savedModels/model3.joblib']